### ISSUE TITLE
C99

### ISSUE THREAD

**Issue by darkzbaron** [daniel1111/HueLibEnt#2]
Getting this error while trying to compile!
``
[  6%] Building C object CMakeFiles/HueEnt.dir/src/hue_rest.c.o
/root/HueLibEnt/src/hue_rest.c: In function ‘free_whitelist’:
/root/HueLibEnt/src/hue_rest.c:83:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (uint i=0; i < ctx->whitelist_count; i++)
   ^
/root/HueLibEnt/src/hue_rest.c:83:3: note: use option -std=c99 or -std=gnu99 to compile your code
/root/HueLibEnt/src/hue_rest.c: In function ‘parse_entertainment_groups_json’:
/root/HueLibEnt/src/hue_rest.c:657:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int n = 0; n < json_object_array_length(obj_param) && n < MAX_LIGHTS_PER_AREA; n++)
       ^
make[2]: *** [CMakeFiles/HueEnt.dir/src/hue_rest.c.o] Error 1
make[1]: *** [CMakeFiles/HueEnt.dir/all] Error 2
make: *** [all] Error 2
``

**Comment by darkzbaron** [comment]
Running WSL on Windows 10

**Comment by daniel1111** [comment]
Hmm, that's odd, not sure why I'm not seeing that!
Could you try building the version in the `set_c99_in_cmakelists` branch? Hopefully that'll fix it. 
If not... I've not used WSL before, but I understand you need to install a distribution to make it work? If so, which one have you got installed?

**Comment by darkzbaron** [comment]
Hi there thanks for the commit. It's progressing Here is what I get. I use Ubuntu 14.04. Really new to both Linux and C++ so this really helps!

``
Scanning dependencies of target HueEnt
[  6%] Building C object CMakeFiles/HueEnt.dir/src/hue_entertainment.c.o
[ 13%] Building C object CMakeFiles/HueEnt.dir/src/hue_rest.c.o
[ 20%] Building C object CMakeFiles/HueEnt.dir/src/dtls.c.o
/root/HueLibEnt/src/dtls.c: In function ‘dtls_connect’:
/root/HueLibEnt/src/dtls.c:235:3: warning: implicit declaration of function ‘DTLS_client_method’ [-Wimplicit-function-declaration]
   ctx->ssl_ctx = SSL_CTX_new(DTLS_client_method());
   ^
/root/HueLibEnt/src/dtls.c:235:3: warning: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast [enabled by default]
In file included from /root/HueLibEnt/include/dtls.h:17:0,
                 from /root/HueLibEnt/src/dtls.c:6:
/usr/include/openssl/ssl.h:1680:10: note: expected ‘const struct SSL_METHOD *’ but argument is of type ‘int’
 SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
          ^
[ 26%] Linking C static library libHueEnt.a
[ 26%] Built target HueEnt
Scanning dependencies of target huevis
[ 33%] Building C object CMakeFiles/huevis.dir/examples/HueVis/huevis.c.o
/root/HueLibEnt/examples/HueVis/huevis.c: In function ‘get_bridge_credentials’:
/root/HueLibEnt/examples/HueVis/huevis.c:135:3: warning: implicit declaration of function ‘config_set_options’ [-Wimplicit-function-declaration]
   config_set_options(&cfg_credentials, (CONFIG_OPTION_AUTOCONVERT));
   ^
[ 40%] Building C object CMakeFiles/huevis.dir/examples/HueVis/input_pulse.c.o
[ 46%] Building C object CMakeFiles/huevis.dir/examples/HueVis/input_squeezelite.c.o
[ 53%] Building C object CMakeFiles/huevis.dir/examples/HueVis/process_cava.c.o
/root/HueLibEnt/examples/HueVis/process_cava.c: In function ‘print_raw_out’:
/root/HueLibEnt/examples/HueVis/process_cava.c:238:4: warning: format not a string literal and no format arguments [-Wformat-security]
    printf(bar_delim);
    ^
/root/HueLibEnt/examples/HueVis/process_cava.c:240:2: warning: format not a string literal and no format arguments [-Wformat-security]
  printf(frame_delim);
  ^
[ 60%] Linking C executable bin/huevis
CMakeFiles/huevis.dir/examples/HueVis/huevis.c.o: In function `get_bridge_credentials':
huevis.c:(.text+0x2d7): undefined reference to `config_set_options'
CMakeFiles/huevis.dir/examples/HueVis/huevis.c.o: In function `main':
huevis.c:(.text+0xab3): undefined reference to `config_set_options'
libHueEnt.a(dtls.c.o): In function `dtls_connect':
dtls.c:(.text+0xa2a): undefined reference to `DTLS_client_method'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/huevis] Error 1
make[1]: *** [CMakeFiles/huevis.dir/all] Error 2
make: *** [all] Error 2
``

**Comment by daniel1111** [comment]
Ah, ok, whilst not end of life yet, Ubuntu 14.04 is really quite old. I'm really surprised it's getting that far if I'm honest, as it depends on cmake >= 3.7 for starters, which isn't available for 14.04 from what I can tell(?)

At the risk of asking a stupid question, is it definitely Ubuntu 14.04 you've got installed? It seems a curious choice for WSL given its age

**Comment by darkzbaron** [comment]
It's installed this way in Windows 10, unfortunately I don't think I can upgrade the version. It's quite comfortable to be able to run Ubuntu in a stock windows, without VM or anything like this but as we both see it's quite limited.

Do you think your compiled code would run on this version on Ubuntu? 

Thanks so much for the support, I really appreciate!

**Comment by daniel1111** [comment]
I've been to:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
but it doesn't look like Ubuntu 14.04 is on the supported list? 

It builds ok in a 18.04 VM, so I'll have a go with 18.04 using WSL and see if I get the same errors

**Comment by daniel1111** [comment]
Ok, so I've tried it with 18.04 using WSL, and builds ok. 
However.. if it's the HueVis part you're after, that depends on pulseaudio, which a quick google suggests isn't easy to get working on WSL (plus the pages I've read relating pulseaudio+wsl were about playback of audio, whilst HueVis needs audio capture).

Essentially, I think it's fair to say that right now the HueLibEnt library works with Ubuntu 18.04 on WSL (as do the bcf + hutil examples), but HueVis doesn't :(

**Comment by darkzbaron** [comment]
Oh my bad. I didn’t see that I could upgrade WSL. I’ll do it. 
Yes I am after the HueVis. 
Ok thanks for the comment. I think I won’t spend too much time trying. There is a 20.04 version of Ubuntu available for WSL, I’ll give a try and if it works I’ll revert. I’ll close the issue, thanks so much for the feedback.

**Comment by darkzbaron** [comment]
Hi there, I have tried to make my WSL Ubuntu use a virtual microphone and stream into this microphone from windows with no success. Alternatively, would you be willing to implement such a solution to make your application more compatible.

Essentially, it would take a streaming url as an input
